import type { ModelCaution, SnapshotRow } from '@pss/pipeline';

export const NO_CAUTION: ModelCaution = {
  borrow: false,
  dividend: false,
  ivRankProxy: false,
  belowParity: false,
  earningsBeforeExpiry: false,
  spotAsync: false,
};

type RowOverride = Partial<Omit<SnapshotRow, 'modelCaution'>> & { modelCaution?: Partial<ModelCaution> };

/** A fully-populated, plausible put row; override any field per test. */
export function mkRow(over: RowOverride = {}): SnapshotRow {
  const base: SnapshotRow = {
    occSymbol: 'AAA   261016P00095000',
    symbol: 'AAA',
    expiration: '2026-10-16',
    strike: 95,
    multiplier: 100,
    dte: 35,
    spot: 100,
    spotAdj: 100,
    bid: 1.9,
    ask: 2.1,
    mid: 2,
    last: 2,
    volume: 800,
    openInterest: 4000,
    quoteAsOf: '2026-09-02T14:00:00.000Z',
    entryCredit: 1.95,
    entryCredit100: 195,
    midCredit: 2,
    slippageK: 0.05,
    iv: 0.3,
    ivVsFitted: 0.01,
    ivRank: 40,
    ivPctile: 45,
    putSkew25d: 0.03,
    delta: -0.25,
    gamma: 0.02,
    thetaDay: -0.04,
    dailyDecay: 0.04,
    vega: 0.1,
    moneynessPct: -5,
    spreadPct: 0.05,
    volOi: 0.2,
    decayYield: 0.02,
    thetaVega: 0.4,
    breakeven: 93.05,
    bePct: -6.95,
    probItm: 0.2,
    pop: 0.8,
    emDistance: 1.1,
    cspCapital100: 9500,
    regtCapital100: 2000,
    annRoc: 0.2,
    capitalBasis: 'csp',
    ev100: 30,
    maxLoss100: 9305,
    evToMaxloss: 0.0032,
    creditToMaxloss: 0.021,
    sigmaF: 0.27,
    vrpHaircut: 0.9,
    mu: 0.04,
    score: 0.5,
    scoreComponents: null,
    modelCaution: { ...NO_CAUTION },
    assignmentWatch: false,
    isCandidate: true,
    excludedReason: null,
  };
  return { ...base, ...over, modelCaution: { ...NO_CAUTION, ...(over.modelCaution ?? {}) } };
}
